// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function ActivityLine({ children, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M9.0001 2.10001C9.38749 2.10001 9.73141 2.34789 9.85391 2.7154L15.0001 18.154L17.1463 11.7154C17.2688 11.3479 17.6127 11.1 18.0001 11.1H22.0001C22.4972 11.1 22.9001 11.5029 22.9001 12C22.9001 12.4971 22.4972 12.9 22.0001 12.9H18.6488L15.8539 21.2846C15.7314 21.6521 15.3875 21.9 15.0001 21.9C14.6127 21.9 14.2688 21.6521 14.1463 21.2846L9.0001 5.84606L6.85391 12.2846C6.73141 12.6521 6.38749 12.9 6.0001 12.9H2.0001C1.50304 12.9 1.1001 12.4971 1.1001 12C1.1001 11.5029 1.50304 11.1 2.0001 11.1H5.35141L8.14628 2.7154C8.26879 2.34789 8.61271 2.10001 9.0001 2.10001Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
