// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function ArrowNarrowLeftLine({
  children,
  ...props
}: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M10.6364 5.36358C10.9878 5.71505 10.9878 6.2849 10.6364 6.63637L6.17277 11.1H20C20.497 11.1 20.9 11.5029 20.9 12C20.9 12.497 20.497 12.9 20 12.9H6.17277L10.6364 17.3636C10.9878 17.7151 10.9878 18.2849 10.6364 18.6364C10.2849 18.9878 9.71505 18.9878 9.36358 18.6364L3.36358 12.6364C3.01211 12.2849 3.01211 11.7151 3.36358 11.3636L9.36358 5.36358C9.71505 5.01211 10.2849 5.01211 10.6364 5.36358Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
