// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function ArrowNarrowDownRightLine({
  children,
  ...props
}: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M5.36358 5.36361C5.71505 5.01214 6.2849 5.01214 6.63637 5.36361L17.1 15.8272V10C17.1 9.50295 17.5029 9.10001 18 9.10001C18.497 9.10001 18.9 9.50295 18.9 10V18C18.9 18.4971 18.497 18.9 18 18.9H9.99998C9.50292 18.9 9.09998 18.4971 9.09998 18C9.09998 17.5029 9.50292 17.1 9.99998 17.1H15.8272L5.36358 6.6364C5.01211 6.28493 5.01211 5.71508 5.36358 5.36361Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
