// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function ArrowDownRightLine({
  children,
  ...props
}: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M6.36358 6.36358C6.71505 6.01211 7.2849 6.01211 7.63637 6.36358L16.1 14.8272V6.99998C16.1 6.50292 16.5029 6.09998 17 6.09998C17.497 6.09998 17.9 6.50292 17.9 6.99998V17C17.9 17.497 17.497 17.9 17 17.9H6.99998C6.50292 17.9 6.09998 17.497 6.09998 17C6.09998 16.5029 6.50292 16.1 6.99998 16.1H14.8272L6.36358 7.63637C6.01211 7.2849 6.01211 6.71505 6.36358 6.36358Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
