// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function ArrowUpLeftLine({
  children,
  ...props
}: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M6.09998 6.99998C6.09998 6.50292 6.50292 6.09998 6.99998 6.09998H17C17.497 6.09998 17.9 6.50292 17.9 6.99998C17.9 7.49703 17.497 7.89998 17 7.89998H9.17277L17.6364 16.3636C17.9878 16.7151 17.9878 17.2849 17.6364 17.6364C17.2849 17.9878 16.7151 17.9878 16.3636 17.6364L7.89998 9.17277V17C7.89998 17.497 7.49703 17.9 6.99998 17.9C6.50292 17.9 6.09998 17.497 6.09998 17V6.99998Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
