// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function ArrowNarrowUpLine({
  children,
  ...props
}: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M11.3636 3.36358C11.7151 3.01211 12.2849 3.01211 12.6364 3.36358L18.6364 9.36358C18.9878 9.71505 18.9878 10.2849 18.6364 10.6364C18.2849 10.9878 17.7151 10.9878 17.3636 10.6364L12.9 6.17277V20C12.9 20.497 12.497 20.9 12 20.9C11.5029 20.9 11.1 20.497 11.1 20V6.17277L6.63637 10.6364C6.2849 10.9878 5.71505 10.9878 5.36358 10.6364C5.01211 10.2849 5.01211 9.71505 5.36358 9.36358L11.3636 3.36358Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
