// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function ArrowDownLine({ children, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M12 4.09998C12.497 4.09998 12.9 4.50292 12.9 4.99998V16.8272L18.3636 11.3636C18.7151 11.0121 19.2849 11.0121 19.6364 11.3636C19.9878 11.7151 19.9878 12.2849 19.6364 12.6364L12.6364 19.6364C12.2849 19.9878 11.7151 19.9878 11.3636 19.6364L4.36358 12.6364C4.01211 12.2849 4.01211 11.7151 4.36358 11.3636C4.71505 11.0121 5.2849 11.0121 5.63637 11.3636L11.1 16.8272V4.99998C11.1 4.50292 11.5029 4.09998 12 4.09998Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
