// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function ArrowUpRightLine({
  children,
  ...props
}: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M6.99998 7.89998C6.50292 7.89998 6.09998 7.49703 6.09998 6.99998C6.09998 6.50292 6.50292 6.09998 6.99998 6.09998H17C17.497 6.09998 17.9 6.50292 17.9 6.99998V17C17.9 17.497 17.497 17.9 17 17.9C16.5029 17.9 16.1 17.497 16.1 17V9.17277L7.63637 17.6364C7.2849 17.9878 6.71505 17.9878 6.36358 17.6364C6.01211 17.2849 6.01211 16.7151 6.36358 16.3636L14.8272 7.89998H6.99998Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
