// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function ArrowNarrowRightLine({
  children,
  ...props
}: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M13.3636 5.36358C13.7151 5.01211 14.2849 5.01211 14.6364 5.36358L20.6364 11.3636C20.9878 11.7151 20.9878 12.2849 20.6364 12.6364L14.6364 18.6364C14.2849 18.9878 13.7151 18.9878 13.3636 18.6364C13.0121 18.2849 13.0121 17.7151 13.3636 17.3636L17.8272 12.9H3.99998C3.50292 12.9 3.09998 12.497 3.09998 12C3.09998 11.5029 3.50292 11.1 3.99998 11.1H17.8272L13.3636 6.63637C13.0121 6.2849 13.0121 5.71505 13.3636 5.36358Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
