// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function ArrowNarrowDownLine({
  children,
  ...props
}: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M12 3.10001C12.497 3.10001 12.9 3.50295 12.9 4.00001V17.8272L17.3636 13.3636C17.7151 13.0121 18.2849 13.0121 18.6364 13.3636C18.9878 13.7151 18.9878 14.2849 18.6364 14.6364L12.6364 20.6364C12.2849 20.9879 11.7151 20.9879 11.3636 20.6364L5.36358 14.6364C5.01211 14.2849 5.01211 13.7151 5.36358 13.3636C5.71505 13.0121 6.2849 13.0121 6.63637 13.3636L11.1 17.8272V4.00001C11.1 3.50295 11.5029 3.10001 12 3.10001Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
