// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function ArrowNarrowUpLeftLine({
  children,
  ...props
}: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M5.09998 5.99998C5.09998 5.50292 5.50292 5.09998 5.99998 5.09998H14C14.497 5.09998 14.9 5.50292 14.9 5.99998C14.9 6.49703 14.497 6.89998 14 6.89998H8.17277L18.6364 17.3636C18.9878 17.7151 18.9878 18.2849 18.6364 18.6364C18.2849 18.9878 17.7151 18.9878 17.3636 18.6364L6.89998 8.17277V14C6.89998 14.497 6.49703 14.9 5.99998 14.9C5.50292 14.9 5.09998 14.497 5.09998 14V5.99998Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
