// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function BarChart02Line({
  children,
  ...props
}: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M18.0001 3.10001C18.4972 3.10001 18.9001 3.50295 18.9001 4.00001V20C18.9001 20.4971 18.4972 20.9 18.0001 20.9C17.503 20.9 17.1001 20.4971 17.1001 20V4.00001C17.1001 3.50295 17.503 3.10001 18.0001 3.10001ZM12.0001 9.10001C12.4972 9.10001 12.9001 9.50295 12.9001 10V20C12.9001 20.4971 12.4972 20.9 12.0001 20.9C11.503 20.9 11.1001 20.4971 11.1001 20V10C11.1001 9.50295 11.503 9.10001 12.0001 9.10001ZM6.0001 15.1C6.49715 15.1 6.9001 15.5029 6.9001 16V20C6.9001 20.4971 6.49715 20.9 6.0001 20.9C5.50304 20.9 5.1001 20.4971 5.1001 20V16C5.1001 15.5029 5.50304 15.1 6.0001 15.1Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
