// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function CheckLine({ children, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M20.6365 5.36358C20.988 5.71505 20.988 6.2849 20.6365 6.63637L9.63649 17.6364C9.28502 17.9878 8.71517 17.9878 8.3637 17.6364L3.3637 12.6364C3.01223 12.2849 3.01223 11.7151 3.3637 11.3636C3.71517 11.0121 4.28502 11.0121 4.63649 11.3636L9.0001 15.7272L19.3637 5.36358C19.7152 5.01211 20.285 5.01211 20.6365 5.36358Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
