// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function ChevronRightLine({
  children,
  ...props
}: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M8.3637 5.36358C8.71517 5.01211 9.28502 5.01211 9.63649 5.36358L15.6365 11.3636C15.988 11.7151 15.988 12.2849 15.6365 12.6364L9.63649 18.6364C9.28502 18.9878 8.71517 18.9878 8.3637 18.6364C8.01223 18.2849 8.01223 17.7151 8.3637 17.3636L13.7273 12L8.3637 6.63637C8.01223 6.2849 8.01223 5.71505 8.3637 5.36358Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
