// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function ChevronLeftLine({
  children,
  ...props
}: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M15.6365 5.36358C15.988 5.71505 15.988 6.2849 15.6365 6.63637L10.2729 12L15.6365 17.3636C15.988 17.7151 15.988 18.2849 15.6365 18.6364C15.285 18.9878 14.7152 18.9878 14.3637 18.6364L8.3637 12.6364C8.01223 12.2849 8.01223 11.7151 8.3637 11.3636L14.3637 5.36358C14.7152 5.01211 15.285 5.01211 15.6365 5.36358Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
