// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function ChevronUpLine({ children, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M11.3637 8.36358C11.7152 8.01211 12.285 8.01211 12.6365 8.36358L18.6365 14.3636C18.988 14.7151 18.988 15.2849 18.6365 15.6364C18.285 15.9878 17.7152 15.9878 17.3637 15.6364L12.0001 10.2728L6.63649 15.6364C6.28502 15.9878 5.71517 15.9878 5.3637 15.6364C5.01223 15.2849 5.01223 14.7151 5.3637 14.3636L11.3637 8.36358Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
