// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function ChevronDownLine({
  children,
  ...props
}: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M5.3637 8.36361C5.71517 8.01214 6.28502 8.01214 6.63649 8.36361L12.0001 13.7272L17.3637 8.36361C17.7152 8.01214 18.285 8.01214 18.6365 8.36361C18.988 8.71508 18.988 9.28493 18.6365 9.6364L12.6365 15.6364C12.285 15.9879 11.7152 15.9879 11.3637 15.6364L5.3637 9.6364C5.01223 9.28493 5.01223 8.71508 5.3637 8.36361Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
