// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function CircleSolid({ children, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        d="M12 1C5.92487 1 1 5.92487 1 12C1 18.0751 5.92487 23 12 23C18.0751 23 23 18.0751 23 12C23 5.92487 18.0751 1 12 1Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
