// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function CircleLine({ children, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M12.0001 2.89998C6.97431 2.89998 2.9001 6.97418 2.9001 12C2.9001 17.0258 6.97431 21.1 12.0001 21.1C17.0259 21.1 21.1001 17.0258 21.1001 12C21.1001 6.97418 17.0259 2.89998 12.0001 2.89998ZM1.1001 12C1.1001 5.98007 5.98019 1.09998 12.0001 1.09998C18.02 1.09998 22.9001 5.98007 22.9001 12C22.9001 18.0199 18.02 22.9 12.0001 22.9C5.98019 22.9 1.1001 18.0199 1.1001 12Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
