// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function EqualLine({ children, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M4.09998 8.99998C4.09998 8.50292 4.50292 8.09998 4.99998 8.09998H19C19.497 8.09998 19.9 8.50292 19.9 8.99998C19.9 9.49703 19.497 9.89998 19 9.89998H4.99998C4.50292 9.89998 4.09998 9.49703 4.09998 8.99998ZM4.09998 15C4.09998 14.5029 4.50292 14.1 4.99998 14.1H19C19.497 14.1 19.9 14.5029 19.9 15C19.9 15.497 19.497 15.9 19 15.9H4.99998C4.50292 15.9 4.09998 15.497 4.09998 15Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
