// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function FilterLinesLine({
  children,
  ...props
}: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M2.09998 5.99998C2.09998 5.50292 2.50292 5.09998 2.99998 5.09998H21C21.497 5.09998 21.9 5.50292 21.9 5.99998C21.9 6.49703 21.497 6.89998 21 6.89998H2.99998C2.50292 6.89998 2.09998 6.49703 2.09998 5.99998ZM5.09998 12C5.09998 11.5029 5.50292 11.1 5.99998 11.1H18C18.497 11.1 18.9 11.5029 18.9 12C18.9 12.497 18.497 12.9 18 12.9H5.99998C5.50292 12.9 5.09998 12.497 5.09998 12ZM8.09998 18C8.09998 17.5029 8.50292 17.1 8.99998 17.1H15C15.497 17.1 15.9 17.5029 15.9 18C15.9 18.497 15.497 18.9 15 18.9H8.99998C8.50292 18.9 8.09998 18.497 8.09998 18Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
