// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function Flag03Line({ children, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        d="M3.9 21.8C3.4 21.8 3 21.4 3 20.9V2.9C3 2.4 3.4 2 3.9 2H19.49C20.09 2 20.48 2 20.85 2.27C21.17 2.51 21.38 2.87 21.41 3.27C21.45 3.72 21.25 4.06 20.95 4.56L18.95 7.89L20.95 11.22C21.26 11.73 21.46 12.07 21.41 12.53C21.37 12.92 21.17 13.29 20.85 13.53C20.48 13.8 20.09 13.8 19.49 13.8H4.8V20.9C4.8 21.4 4.4 21.8 3.9 21.8ZM4.8 12H19.31L17.37 8.77C17.26 8.58 17.16 8.42 17.11 8.2C17.07 8 17.07 7.79 17.11 7.6C17.16 7.38 17.26 7.22 17.37 7.03L19.31 3.8H4.8V12Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
