// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function GitCommitSolid({
  children,
  ...props
}: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M16.9 11C16.4367 8.71776 14.419 7 12 7C9.58104 7 7.56329 8.71776 7.10002 11H2.00018C1.4479 11 1.00018 11.4477 1.00018 12C1.00018 12.5523 1.4479 13 2.00018 13H7.10002C7.56329 15.2822 9.58104 17 12 17C14.419 17 16.4367 15.2822 16.9 13H22C22.5523 13 23 12.5523 23 12C23 11.4477 22.5523 11 22 11H16.9Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
