// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function GitCommitLine({ children, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M12 8.9001C10.2879 8.9001 8.89999 10.288 8.89999 12.0001C8.89999 13.7122 10.2879 15.1001 12 15.1001C13.7121 15.1001 15.1 13.7122 15.1 12.0001C15.1 10.288 13.7121 8.9001 12 8.9001ZM7.18247 11.1001C7.60506 8.82377 9.60123 7.1001 12 7.1001C14.3988 7.1001 16.3949 8.82377 16.8175 11.1001H22C22.4971 11.1001 22.9 11.503 22.9 12.0001C22.9 12.4972 22.4971 12.9001 22 12.9001H16.8175C16.3949 15.1764 14.3988 16.9001 12 16.9001C9.60123 16.9001 7.60506 15.1764 7.18247 12.9001H2.00019C1.50313 12.9001 1.10019 12.4972 1.10019 12.0001C1.10019 11.503 1.50313 11.1001 2.00019 11.1001H7.18247Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
