// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function InfinityLine({ children, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        d="M18.08 16.8C15.47 16.8 13.62 15.06 11.9 13.22C10.17 15.04 8.16 16.8 5.34 16.8C2.52 16.8 1 14.33 1 11.9C1 9.47 2.49 7 5.34 7C8.19 7 10.17 8.76 11.9 10.58C13.62 8.74 15.47 7 18.08 7C21.18 7 22.8 9.46 22.8 11.9C22.8 14.34 21.18 16.8 18.08 16.8ZM13.13 11.9C14.67 13.55 16.17 15 18.08 15C19 15 19.73 14.69 20.26 14.07C20.73 13.52 21 12.73 21 11.9C21 10.36 20.1 8.8 18.08 8.8C16.17 8.8 14.67 10.25 13.13 11.9ZM5.34 8.8C4.56 8.8 3.93 9.1 3.48 9.7C3.05 10.26 2.81 11.06 2.81 11.9C2.81 13.05 3.34 15 5.35 15C7.51 15 9.1 13.58 10.68 11.9C9.1 10.22 7.51 8.8 5.35 8.8H5.34Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
