// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function Menu05Line({ children, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M2.09998 8.49998C2.09998 8.00292 2.50292 7.59998 2.99998 7.59998H21C21.497 7.59998 21.9 8.00292 21.9 8.49998C21.9 8.99703 21.497 9.39998 21 9.39998H2.99998C2.50292 9.39998 2.09998 8.99703 2.09998 8.49998ZM2.09998 15.5C2.09998 15.0029 2.50292 14.6 2.99998 14.6H21C21.497 14.6 21.9 15.0029 21.9 15.5C21.9 15.997 21.497 16.4 21 16.4H2.99998C2.50292 16.4 2.09998 15.997 2.09998 15.5Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
