// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function Menu01Line({ children, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M2.09998 5.99998C2.09998 5.50292 2.50292 5.09998 2.99998 5.09998H21C21.497 5.09998 21.9 5.50292 21.9 5.99998C21.9 6.49703 21.497 6.89998 21 6.89998H2.99998C2.50292 6.89998 2.09998 6.49703 2.09998 5.99998ZM2.09998 12C2.09998 11.5029 2.50292 11.1 2.99998 11.1H21C21.497 11.1 21.9 11.5029 21.9 12C21.9 12.497 21.497 12.9 21 12.9H2.99998C2.50292 12.9 2.09998 12.497 2.09998 12ZM2.09998 18C2.09998 17.5029 2.50292 17.1 2.99998 17.1H21C21.497 17.1 21.9 17.5029 21.9 18C21.9 18.497 21.497 18.9 21 18.9H2.99998C2.50292 18.9 2.09998 18.497 2.09998 18Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
