// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function MinusLine({ children, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M4.09998 12C4.09998 11.5029 4.50292 11.1 4.99998 11.1H19C19.497 11.1 19.9 11.5029 19.9 12C19.9 12.497 19.497 12.9 19 12.9H4.99998C4.50292 12.9 4.09998 12.497 4.09998 12Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
