// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function PlaceholderLine({
  children,
  ...props
}: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M12 2.89998C6.97418 2.89998 2.89998 6.97418 2.89998 12C2.89998 17.0258 6.97418 21.1 12 21.1C17.0258 21.1 21.1 17.0258 21.1 12C21.1 6.97418 17.0258 2.89998 12 2.89998ZM1.09998 12C1.09998 5.98007 5.98007 1.09998 12 1.09998C18.0199 1.09998 22.9 5.98007 22.9 12C22.9 18.0199 18.0199 22.9 12 22.9C5.98007 22.9 1.09998 18.0199 1.09998 12Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
