// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function SearchSmLine({ children, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M9.99998 3.89998C6.63104 3.89998 3.89998 6.63104 3.89998 9.99998C3.89998 13.3689 6.63104 16.1 9.99998 16.1C13.3689 16.1 16.1 13.3689 16.1 9.99998C16.1 6.63104 13.3689 3.89998 9.99998 3.89998ZM2.09998 9.99998C2.09998 5.63693 5.63693 2.09998 9.99998 2.09998C14.363 2.09998 17.9 5.63693 17.9 9.99998C17.9 11.8572 17.2591 13.5648 16.1864 14.9135L21.6364 20.3636C21.9878 20.7151 21.9878 21.2849 21.6364 21.6364C21.2849 21.9878 20.715 21.9878 20.3636 21.6364L14.9136 16.1863C13.5648 17.2591 11.8573 17.9 9.99998 17.9C5.63693 17.9 2.09998 14.363 2.09998 9.99998Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
