// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function SlashCircle01Line({
  children,
  ...props
}: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M4.96026 6.23309C3.67272 7.80296 2.89998 9.81124 2.89998 12C2.89998 17.0258 6.97418 21.1 12 21.1C14.1887 21.1 16.197 20.3273 17.7669 19.0397L4.96026 6.23309ZM6.23306 4.96029L19.0397 17.7669C20.3272 16.1971 21.1 14.1888 21.1 12C21.1 6.97421 17.0258 2.90001 12 2.90001C9.81121 2.90001 7.80292 3.67275 6.23306 4.96029ZM1.09998 12C1.09998 5.9801 5.98007 1.10001 12 1.10001C18.0199 1.10001 22.9 5.9801 22.9 12C22.9 18.0199 18.0199 22.9 12 22.9C5.98007 22.9 1.09998 18.0199 1.09998 12Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
