// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function SlashDividerLine({
  children,
  ...props
}: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M17.4025 1.19501C17.8471 1.4173 18.0273 1.9579 17.805 2.40248L7.80504 22.4025C7.58274 22.8471 7.04214 23.0273 6.59756 22.805C6.15298 22.5827 5.97278 22.0421 6.19507 21.5975L16.1951 1.5975C16.4174 1.15292 16.958 0.972715 17.4025 1.19501Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
