// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function TerminalLine({ children, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M3.3636 4.3637C3.71508 4.01223 4.28492 4.01223 4.6364 4.3637L10.6364 10.3637C10.9879 10.7152 10.9879 11.285 10.6364 11.6365L4.6364 17.6365C4.28492 17.988 3.71508 17.988 3.3636 17.6365C3.01213 17.285 3.01213 16.7152 3.3636 16.3637L8.72721 11.0001L3.3636 5.63649C3.01213 5.28502 3.01213 4.71517 3.3636 4.3637ZM11.1 19.0001C11.1 18.503 11.5029 18.1001 12 18.1001H20C20.4971 18.1001 20.9 18.503 20.9 19.0001C20.9 19.4972 20.4971 19.9001 20 19.9001H12C11.5029 19.9001 11.1 19.4972 11.1 19.0001Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
