// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function Toggle01LeftSolid({
  children,
  ...props
}: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M7 6C3.68629 6 1 8.68629 1 12C1 15.3137 3.68629 18 7 18H17C20.3137 18 23 15.3137 23 12C23 8.68629 20.3137 6 17 6H7ZM11.4722 16C12.4223 14.9385 13 13.5367 13 12C13 10.4633 12.4223 9.06151 11.4722 8H17C19.2091 8 21 9.79086 21 12C21 14.2091 19.2091 16 17 16H11.4722Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
