// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function TrendDown02Line({
  children,
  ...props
}: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M6.3637 6.36358C6.71517 6.01211 7.28502 6.01211 7.63649 6.36358L16.1001 14.8272V6.99998C16.1001 6.50292 16.503 6.09998 17.0001 6.09998C17.4972 6.09998 17.9001 6.50292 17.9001 6.99998V17C17.9001 17.497 17.4972 17.9 17.0001 17.9H7.0001C6.50304 17.9 6.1001 17.497 6.1001 17C6.1001 16.5029 6.50304 16.1 7.0001 16.1H14.8273L6.3637 7.63637C6.01223 7.2849 6.01223 6.71505 6.3637 6.36358Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
