// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function TrendUp02Line({ children, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M7.0001 7.89998C6.50304 7.89998 6.1001 7.49703 6.1001 6.99998C6.1001 6.50292 6.50304 6.09998 7.0001 6.09998H17.0001C17.4972 6.09998 17.9001 6.50292 17.9001 6.99998V17C17.9001 17.497 17.4972 17.9 17.0001 17.9C16.503 17.9 16.1001 17.497 16.1001 17V9.17277L7.63649 17.6364C7.28502 17.9878 6.71517 17.9878 6.3637 17.6364C6.01223 17.2849 6.01223 16.7151 6.3637 16.3636L14.8273 7.89998H7.0001Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
