// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function XCloseLine({ children, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M5.36358 5.36358C5.71505 5.01211 6.2849 5.01211 6.63637 5.36358L12 10.7272L17.3636 5.36358C17.7151 5.01211 18.2849 5.01211 18.6364 5.36358C18.9878 5.71505 18.9878 6.2849 18.6364 6.63637L13.2728 12L18.6364 17.3636C18.9878 17.7151 18.9878 18.2849 18.6364 18.6364C18.2849 18.9878 17.7151 18.9878 17.3636 18.6364L12 13.2728L6.63637 18.6364C6.2849 18.9878 5.71505 18.9878 5.36358 18.6364C5.01211 18.2849 5.01211 17.7151 5.36358 17.3636L10.7272 12L5.36358 6.63637C5.01211 6.2849 5.01211 5.71505 5.36358 5.36358Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
