// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
import type { SVGProps } from "react";

export function XLine({ children, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M6.36358 6.36358C6.71505 6.01211 7.2849 6.01211 7.63637 6.36358L12 10.7272L16.3636 6.36358C16.7151 6.01211 17.2849 6.01211 17.6364 6.36358C17.9878 6.71505 17.9878 7.2849 17.6364 7.63637L13.2728 12L17.6364 16.3636C17.9878 16.7151 17.9878 17.2849 17.6364 17.6364C17.2849 17.9878 16.7151 17.9878 16.3636 17.6364L12 13.2728L7.63637 17.6364C7.2849 17.9878 6.71505 17.9878 6.36358 17.6364C6.01211 17.2849 6.01211 16.7151 6.36358 16.3636L10.7272 12L6.36358 7.63637C6.01211 7.2849 6.01211 6.71505 6.36358 6.36358Z"
        fill="currentColor"
      />
      {children}
    </svg>
  );
}
