// src/icons/svg/*.svg + scripts/data/icons.json → 컴포넌트/레지스트리/타입/배럴 생성.
// 네트워크 없음. 결정론적. 언제든 재실행 가능.
//
// 실행: node scripts/build-icons.mjs [--check]
//   --check : 파일을 쓰지 않고 누락/이상치만 리포트 (CI 용)

import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { buildModel } from "./lib/icon-names.mjs";
import { normalize } from "./lib/svg-to-jsx.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const DATA_FILE = join(ROOT, "scripts/data/icons.json");
const SVG_DIR = join(ROOT, "src/icons/svg");
const COMPONENTS_DIR = join(ROOT, "src/icons/components");

const CHECK = process.argv.slice(2).includes("--check");
const BANNER = "// AUTO-GENERATED by scripts/build-icons.mjs — do not edit.\n";

async function main() {
  const rows = JSON.parse(await readFile(DATA_FILE, "utf8"));
  const { icons, duplicates } = buildModel(rows);
  console.log(
    `▶ 아이콘 ${icons.length}개 (중복 제외), 중복 ${duplicates.length}건`,
  );

  const missing = icons.filter(
    (i) => !existsSync(join(SVG_DIR, `${i.file}.svg`)),
  );
  if (missing.length) {
    console.error(
      `❌ 원본 SVG 누락 ${missing.length}건 — 먼저 npm run icons:fetch`,
    );
    for (const i of missing.slice(0, 20))
      console.error(`   ${i.file}.svg  (${i.key})`);
    if (missing.length > 20) console.error(`   … 외 ${missing.length - 20}건`);
    process.exit(1);
  }

  const warnings = [];
  const built = [];
  for (const icon of icons) {
    const raw = await readFile(join(SVG_DIR, `${icon.file}.svg`), "utf8");
    let res;
    try {
      res = normalize(raw, { file: icon.file });
    } catch (e) {
      console.error(`❌ 정규화 실패: ${icon.file}.svg — ${e.message}`);
      process.exit(1);
    }
    for (const w of res.warnings) warnings.push(`${icon.file}: ${w}`);
    built.push({ ...icon, ...res });
  }

  if (warnings.length) {
    console.warn(`⚠ 변환 경고 ${warnings.length}건:`);
    for (const w of warnings.slice(0, 40)) console.warn(`   ${w}`);
    if (warnings.length > 40) console.warn(`   … 외 ${warnings.length - 40}건`);
  }

  if (CHECK) {
    console.log("✅ --check 통과 (파일 미기록)");
    return;
  }

  // ── 기존 생성물 정리 후 재생성 ───────────────────────────
  await mkdir(COMPONENTS_DIR, { recursive: true });
  for (const f of await readdir(COMPONENTS_DIR).catch(() => [])) {
    if (f.endsWith(".tsx") || f === "index.ts")
      await rm(join(COMPONENTS_DIR, f));
  }

  // 개별 컴포넌트
  for (const icon of built) {
    const src =
      BANNER +
      `import type { SVGProps } from 'react'\n\n` +
      `export function ${icon.pascal}({ children, ...props }: SVGProps<SVGSVGElement>) {\n` +
      `  return (\n` +
      `    <svg viewBox="${icon.viewBox}" fill="none" {...props}>\n` +
      `      ${icon.jsxChildren}\n` +
      `      {children}\n` +
      `    </svg>\n` +
      `  )\n` +
      `}\n`;
    await writeFile(join(COMPONENTS_DIR, `${icon.file}.tsx`), src);
  }

  // 배럴
  await writeFile(
    join(COMPONENTS_DIR, "index.ts"),
    BANNER +
      built.map((i) => `export { ${i.pascal} } from './${i.file}'`).join("\n") +
      "\n",
  );

  // iconNames.ts
  await writeFile(
    join(ROOT, "src/icons/iconNames.ts"),
    BANNER +
      `export const ICON_NAMES = [\n` +
      built.map((i) => `  '${i.key}',`).join("\n") +
      `\n] as const\n\n` +
      `export type IconName = (typeof ICON_NAMES)[number]\n`,
  );

  // iconRegistry.ts
  await writeFile(
    join(ROOT, "src/icons/iconRegistry.ts"),
    BANNER +
      `import type { ComponentType, SVGProps } from 'react'\n\n` +
      `import type { IconName } from './iconNames'\n` +
      built
        .map((i) => `import { ${i.pascal} } from './components/${i.file}'`)
        .join("\n") +
      `\n\n` +
      `export type IconComponent = ComponentType<SVGProps<SVGSVGElement>>\n\n` +
      `export const iconRegistry: Record<IconName, IconComponent> = {\n` +
      built.map((i) => `  '${i.key}': ${i.pascal},`).join("\n") +
      `\n}\n`,
  );

  console.log(
    `✅ 생성 완료 — 컴포넌트 ${built.length} + index.ts + iconNames.ts + iconRegistry.ts`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
